### ISSUE TITLE
I can't find installation folders 

### ISSUE THREAD

**Issue by tomkimsour** [ichigoi7e/indoor_mapping#3]
I'm trying to test your project to understand how octomap is working but i can't build certain package because some commands goes into directories that are not in the repo.

Is it possible to have further explainations ?

Exemple :
```
$ sudo apt-get install build-essential libgtk2.0-dev libvtk5-dev libjpeg-dev libtiff5-dev libjasper-dev libopenexr-dev libtbb-dev python-numpy python-matplotlib
$ cd opencv-3.2.0
```

**Comment by necusjz** [comment]
Hi @tomkimsour ,

Thanks for pointing out this issue, you can find the corresponding release packages easily via GitHub, as follows:
- opencv-3.2.0: https://github.com/opencv/opencv/releases/tag/3.2.0;
- pcl-pcl-1.8.1: https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.8.1;
- VTK-8.1.1: https://github.com/Kitware/VTK/releases/tag/v8.1.1;

You may aware that some versions are a bit old, since it was a practice in 2018. You can consider upgrading them as appropriate.

Anyway, happy trying!
